#!/bin/sh
cat /etc/passwd | grep -v '#' | awk -F':' '{ $1=$1","; $3=$3",";
print $1, $3, $6 }'
# note "grep -v '#'" is not necessary when the script is run on Debian VM
# as there is no comment lines (first 10 lines in mac os)
