#!/bin/sh
# add the following script to your cron table (crontab)
# using "0 0 * * * root /path/to/script >> /etc/crontab"

file=/etc/crontab
md5old=/etc/crontab_copy

if [[ ! -f $md5old ]]; then
	touch $md5old
fi

filemd5=`md5sum $file | cut -d " " -f1`

if [ -z $filemd5 ]; then
	echo "Error : filemd5 is empty"
	exit 1
else
	if [ -f $md5old ]; then
		savedmd5=`cat $md5old`
		if [ -z $savedmd5 ]; then
			echo "Error : savedmd5 is empty"
			exit 1
		fi
		if [ "$savedmd5" == "$filemd5" ]; then
			:
		else
			echo "crontab file has been changed" | mail -s "Alert" root
		fi
	else
		:
	fi
fi
echo $filemd5 > $md5old
